In [63]:
import pandas as pd

orders = pd.read_csv("../data/csv files/olist_orders_dataset.csv")

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [64]:
orders.shape

(99441, 8)

In [65]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [66]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [67]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [68]:
orders['order_status'].value_counts()

delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: order_status, dtype: int64

In [69]:
orders['order_id'].duplicated().sum()

0

In [70]:
orders.duplicated().sum()

0

In [71]:
orders['order_purchase_timestamp'].min()

'2016-09-04 21:15:19'

In [72]:
orders['order_purchase_timestamp'].max()

'2018-10-17 17:30:18'

In [73]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [74]:
orders['order_status'].value_counts()

delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: order_status, dtype: int64

In [75]:
orders['order_id'].duplicated().sum()

0

In [76]:
orders.duplicated().sum()

0

In [77]:
orders['order_purchase_timestamp'].min()

'2016-09-04 21:15:19'

In [78]:
orders['order_purchase_timestamp'].max()

'2018-10-17 17:30:18'

In [79]:
orders['order_id'].isnull().sum()

0

In [80]:
orders['order_id'].nunique()

99441

In [81]:
orders['order_id'].duplicated().sum()

0

In [82]:
orders['order_id'].head(10)

0    e481f51cbdc54678b7cc49136f2d6af7
1    53cdb2fc8bc7dce0b6741e2150273451
2    47770eb9100c2d0c44946d9cf07ec65d
3    949d5b44dbf5de918fe9c16f97b45f8a
4    ad21c59c0840e6cb83a9ceb5573f8159
5    a4591c265e18cb1dcee52889e2d8acc3
6    136cce7faa42fdb2cefd53fdc79a6098
7    6514b8ad8028c9f2cc2374ded245783f
8    76c6e866289321a7c93b82b54852dc33
9    e69bfb5eb88e0ed6a785585b27e16dbf
Name: order_id, dtype: object

In [83]:
orders_clean = orders.copy()

In [84]:
date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_columns:
    orders_clean[col] = pd.to_datetime(
        orders_clean[col],
        errors='coerce'
    )

In [85]:
orders_clean[date_columns].isnull().sum()

order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [86]:
orders_clean.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [87]:
invalid_approval = (
    orders_clean['order_approved_at'].notna() &
    (orders_clean['order_approved_at'] < orders_clean['order_purchase_timestamp'])
)

invalid_approval.sum()

0

In [88]:
invalid_carrier = (
    orders_clean['order_delivered_carrier_date'].notna() &
    (orders_clean['order_delivered_carrier_date'] < orders_clean['order_purchase_timestamp'])
)

invalid_carrier.sum()

166

In [89]:
invalid_customer_delivery = (
    orders_clean['order_delivered_customer_date'].notna() &
    (orders_clean['order_delivered_customer_date'] < orders_clean['order_purchase_timestamp'])
)

invalid_customer_delivery.sum()

0

In [90]:
invalid_delivery_sequence = (
    orders_clean['order_delivered_customer_date'].notna() &
    orders_clean['order_delivered_carrier_date'].notna() &
    (orders_clean['order_delivered_customer_date'] <
     orders_clean['order_delivered_carrier_date'])
)

invalid_delivery_sequence.sum()

23

In [91]:
orders_clean.groupby('order_status')[
    [
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date'
    ]
].count()

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,2,0,0
canceled,484,75,6
created,0,0,0
delivered,96464,96476,96470
invoiced,314,0,0
processing,301,0,0
shipped,1107,1107,0
unavailable,609,0,0

In [92]:
orders_clean['order_status'].value_counts()

delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: order_status, dtype: int64

In [93]:
orders_clean['invalid_date_sequence'] = (
    invalid_approval |
    invalid_carrier |
    invalid_customer_delivery |
    invalid_delivery_sequence
)

In [94]:
orders_clean['invalid_date_sequence'].value_counts()

False    99252
True       189
Name: invalid_date_sequence, dtype: int64